// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhd4R48L0INDj1hcIzdUaxbRb16gxAQCs',
    appId: '1:863065831908:web:7a6a56cf424ab3185ceff1',
    messagingSenderId: '863065831908',
    projectId: 'healthandsafety-fb8a0',
    authDomain: 'healthandsafety-fb8a0.firebaseapp.com',
    storageBucket: 'healthandsafety-fb8a0.appspot.com',
    measurementId: 'G-YF4WHNPXRL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNpgGgFuGqklhu-QKm5F2CirDWA9Fyo4E',
    appId: '1:863065831908:android:2f1f6756f567ae9f5ceff1',
    messagingSenderId: '863065831908',
    projectId: 'healthandsafety-fb8a0',
    storageBucket: 'healthandsafety-fb8a0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChpy3tkYDdqOtYt2nw4RUOzUeMccc9vw4',
    appId: '1:863065831908:ios:909370631613eafd5ceff1',
    messagingSenderId: '863065831908',
    projectId: 'healthandsafety-fb8a0',
    storageBucket: 'healthandsafety-fb8a0.appspot.com',
    iosBundleId: 'com.erkanozturk.hseapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChpy3tkYDdqOtYt2nw4RUOzUeMccc9vw4',
    appId: '1:863065831908:ios:d07fbd00d8a1399e5ceff1',
    messagingSenderId: '863065831908',
    projectId: 'healthandsafety-fb8a0',
    storageBucket: 'healthandsafety-fb8a0.appspot.com',
    iosBundleId: 'com.erkanozturk.hseapp.RunnerTests',
  );
}
