// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhd4R48L0INDj1hcIzdUaxbRb16gxAQCs',
    appId: '1:863065831908:web:1006c5f639620be55ceff1',
    messagingSenderId: '863065831908',
    projectId: 'healthandsafety-fb8a0',
    authDomain: 'healthandsafety-fb8a0.firebaseapp.com',
    storageBucket: 'healthandsafety-fb8a0.appspot.com',
    measurementId: 'G-J9DGZ4R8YF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNpgGgFuGqklhu-QKm5F2CirDWA9Fyo4E',
    appId: '1:863065831908:android:418e3d615e5b833f5ceff1',
    messagingSenderId: '863065831908',
    projectId: 'healthandsafety-fb8a0',
    storageBucket: 'healthandsafety-fb8a0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChpy3tkYDdqOtYt2nw4RUOzUeMccc9vw4',
    appId: '1:863065831908:ios:f3eaf32ef156c2a95ceff1',
    messagingSenderId: '863065831908',
    projectId: 'healthandsafety-fb8a0',
    storageBucket: 'healthandsafety-fb8a0.appspot.com',
    iosBundleId: 'com.example.adminDashboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChpy3tkYDdqOtYt2nw4RUOzUeMccc9vw4',
    appId: '1:863065831908:ios:5dc747d46a8180415ceff1',
    messagingSenderId: '863065831908',
    projectId: 'healthandsafety-fb8a0',
    storageBucket: 'healthandsafety-fb8a0.appspot.com',
    iosBundleId: 'com.example.adminDashboard.RunnerTests',
  );
}
