// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3rK3cy-inJSDASFqp9lNJm0qrql3Z11E',
    appId: '1:37699514273:web:e1eb98bae74537039aa5e0',
    messagingSenderId: '37699514273',
    projectId: 'multi-store-ea764',
    authDomain: 'multi-store-ea764.firebaseapp.com',
    storageBucket: 'multi-store-ea764.appspot.com',
    measurementId: 'G-FMQJKPWXX8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHs_DPN9PHw2C1gKr93PoYXDX1GBd3I3o',
    appId: '1:37699514273:android:0f49dc8dcd84f6109aa5e0',
    messagingSenderId: '37699514273',
    projectId: 'multi-store-ea764',
    storageBucket: 'multi-store-ea764.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQMK_xMuq35qD_MP4EmKaqFV98BBqz0oc',
    appId: '1:37699514273:ios:d2a48b1be8bce50d9aa5e0',
    messagingSenderId: '37699514273',
    projectId: 'multi-store-ea764',
    storageBucket: 'multi-store-ea764.appspot.com',
    androidClientId: '37699514273-pg1jg0rqklbmpm2ie1cqa3faujfb5vli.apps.googleusercontent.com',
    iosBundleId: 'com.erkanozturk1903.multistoreApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQMK_xMuq35qD_MP4EmKaqFV98BBqz0oc',
    appId: '1:37699514273:ios:7db75360ba3405649aa5e0',
    messagingSenderId: '37699514273',
    projectId: 'multi-store-ea764',
    storageBucket: 'multi-store-ea764.appspot.com',
    androidClientId: '37699514273-pg1jg0rqklbmpm2ie1cqa3faujfb5vli.apps.googleusercontent.com',
    iosBundleId: 'com.erkanozturk1903.multistoreApp.RunnerTests',
  );
}
